name: CI
on:
  push:
    branches:
      - main
permissions:
  contents: write
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com
          scope: "@tonishi0922"
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build
      - name: Check token
        run: echo ${{secrets.NPM_TOKEN}}
      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
